# Default values for innovation-workshop.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  external:    
    repository: image-registry.openshift-image-registry.svc:5000/helm-sandbox/springboot-app:1.0 
  pullPolicy: Always

microservice:
  name: springboot-app
  image:
    tag: "1.0"
  limits:
    memory: 1500Mi
    cpu: 1000m
  request:
    memory: 1024Mi
    cpu: 500m
  livenessProbe:
      path: ""
  readinessProbe:
      path: ""

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
