apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: {{ .Values.microservice.name }}
    app.kubernetes.io/component: {{ .Values.microservice.name }}
    app.kubernetes.io/instance: {{ .Values.microservice.name }}
  name: {{ .Values.microservice.name }}
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.microservice.name }}:{{ .Values.microservice.image.tag }}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: {{ .Values.microservice.image.baseimage }}
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5